[workspace]
members = [
    "crates/jjs-modules",
    "modules/node-http",
    "modules/node-fs",
    "modules/node-path",
    "modules/express",
    "modules/hazelcast",
    "modules/rate-limit",
    "modules/json-schema",
    "modules/service",
    "modules/text",
    "modules/schedule",
    "modules/tps-fetch",
    "modules/tps-evidence",
    "modules/tps-notify",
    "modules/tps-secrets",
    "modules/jjs-crypto",
    "modules/resvg",
    "modules/sqlite3",
    "modules/better-sqlite3",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
jjs = { git = "https://github.com/userlite/jjs.git", rev = "6d475b9", default-features = false }
jjs-module-api = { git = "https://github.com/userlite/jjs.git", rev = "6d475b9" }
