[package]
name = "jjs-module-express"
version = "0.1.0"
edition = "2021"
description = "Rust-native Express-compatible module for JJS"
license = "MIT"

[dependencies]
percent-encoding = "2"
jjs-module-api.workspace = true
jjs-module-node-querystring = { path = "../node-querystring" }

[dev-dependencies]
jjs.workspace = true
jjs-module-node-http = { path = "../node-http" }

jjs-module-node-buffer = { path = "../node-buffer" }
